package edu.isi.ldviews.query;

public enum QueryType {
	TRACE_COMBINED,
	TRACE_COMBINED_NO_AGGREGATIONS,
	TRACE_COMBINED_NO_USERDELAY,
	COMBINED,
	COMBINED_NO_AGGREGATIONS,
	COMBINED_NO_USERDELAY,
	SEARCH,
	FACET,
	FACET_MISSING,
	AGGREGATE,
	USERDELAY
}
